### ISSUE TITLE
[Feature Request] - Add support for Helm plugins

### ISSUE THREAD

**Issue by dkirrane** [geerlingguy/ansible-role-helm#9]
Could this be updated to support Helm plugins e.g. [Helm diff](https://github.com/databus23/helm-diff)

`helm plugin install https://github.com/databus23/helm-diff`

**Comment by geerlingguy** [comment]
Possibly; Ansible's kubernetes.core collection does include `helm_plugin`: https://docs.ansible.com/ansible/latest/collections/kubernetes/core/helm_plugin_module.html#ansible-collections-kubernetes-core-helm-plugin-module (as well as `helm_plugin_info`).
